"""
Django settings for Northwind project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dw1uo9lh@7ll@%f$s7yu)-wth+duj!&aby_h53o-we4h_aw4zp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1, localhost').split(',')
if not DEBUG:
    # Add your Azure Web App URL here for production
    # Example: your-northwind-app.azurewebsites.net
    # You might also want to add '*' for testing in Azure initially, but remove for production.
    ALLOWED_HOSTS.append('northwind-django-mp-eeded6bzb6a6agen.uksouth-01.azurewebsites.net')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    'categories',
    'customers',
    'employees',
    'orders',
    'products',
    'regions',
    'shippers',
    'suppliers',
    'dashboard',
    'corsheaders'
]

MIGRATION_MODULES = {
    'categories': None,
    'customers': None,
    'employees': None,
    'orders': None,
    'products': None,
    'regions': None,
    'shippers': None,
    'suppliers': None,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = 'Northwind.Northwind.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Northwind.Northwind.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


DATABASES = {
    'default': {   
        'ENGINE': 'mssql',   
        'NAME': os.getenv('AZURESQL_DATABASE'),   
        'USER': os.getenv('AZURESQL_USER'),   
        'PASSWORD': os.getenv('AZURESQL_PASSWORD'),   
        'HOST': os.getenv('AZURESQL_HOSTNAME'),   
        'PORT': os.getenv('AZURESQL_PORT'),
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            #'authentication': 'ActiveDirectoryDefault',
            'encrypt': True,
            'trust_server_certificate': False,
            'ssl': {'ca': r'/app/BaltimoreCyberTrustRoot.crt.pem'},
        }         
    }  
}
'''
DATABASES = {
    'default': {   
        'ENGINE': 'mssql',   
        'NAME': os.getenv('AZURESQL_DATABASE'),   
        'USER': os.getenv('AZURESQL_USER'),   
        'PASSWORD': os.getenv('AZURESQL_PASSWORD'),   
        'HOST': os.getenv('AZURESQL_HOSTNAME'),   
        'PORT': os.getenv('AZURESQL_PORT'),
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'encrypt': True,
            'trust_server_certificate': False,
        }         
    }  
}
'''

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "https://white-rock-0ecf1790f.6.azurestaticapps.net"
]

DASHBOARD_CACHE_TIMEOUT = 300

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        #'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day'
    }
}

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')