# Generated by Django 5.0.14 on 2025-05-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
