# Generated by Django 5.0.14 on 2025-05-08 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
        ('products', '0001_initial'),
        ('shippers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('required_date', models.DateField()),
                ('shipped_date', models.DateField(blank=True, null=True)),
                ('freight', models.DecimalField(decimal_places=4, max_digits=19)),
                ('ship_name', models.CharField(max_length=255)),
                ('ship_address', models.CharField(max_length=255)),
                ('ship_city', models.CharField(max_length=100)),
                ('ship_region', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_postal_code', models.CharField(max_length=20)),
                ('ship_country', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('ship_via', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shippers.shipper')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('discount', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
